# Generated by Django 6.0.3 on 2026-03-27 23:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0002_weeklylog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='weeklylog',
            unique_together={('student', 'week_number')},
        ),
    ]
